In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report

In [3]:
data_snp_phenotype = pd.read_csv('../data/data_snp_phenotype_012.csv', sep=',')

In [4]:
data_snp_phenotype

,Accession,NC_024459.2,NC_024459.2.1,NC_024459.2.2,NC_024459.2.3,NC_024459.2.4,NC_024459.2.5,NC_024459.2.6,NC_024459.2.7,NC_024459.2.8,...,NC_024468.2.13199,NC_024468.2.13200,NC_024468.2.13201,NC_024468.2.13202,NC_024468.2.13203,NC_024468.2.13204,NC_024468.2.13205,NC_024468.2.13206,NC_024468.2.13207,Heterotic group
0,CRR504157,1|0,1|1,1|0,0|1,1|1,1|0,1|0,1|0,1|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,NSS
1,CRR504163,1|0,1|1,1|0,1|1,1|1,1|0,1|0,1|0,1|0,...,0|1,0|1,1|1,0|0,1|1,1|1,1|1,0|0,0|0,SPT
2,CRR504172,1|0,1|0,1|0,1|1,1|1,0|1,0|1,0|1,0|1,...,1|0,0|0,0|0,0|0,0|1,0|1,0|1,1|0,1|0,NSS
3,CRR504174,0|1,0|1,0|1,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,PB
4,CRR504181,0|0,1|1,0|0,1|1,1|1,1|0,1|0,1|0,1|0,...,1|1,1|1,1|1,1|0,1|1,1|1,1|1,0|1,0|1,PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,CRR505744,0|1,1|1,0|1,1|1,1|1,0|1,0|1,0|1,0|1,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|1,0|1,PA
601,CRR505746,0|1,1|1,0|1,1|1,1|1,0|1,0|1,0|1,0|1,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,1|0,1|0,PA
602,CRR505747,1|0,1|1,1|0,1|1,1|1,1|0,1|0,1|0,1|0,...,0|0,1|1,1|1,0|0,1|1,1|1,1|1,1|0,1|0,PA
603,CRR505752,1|0,1|0,1|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,1|0,1|0,PA
604,CRR505754,0|1,0|1,0|1,0|1,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|1,0|1,NSS

In [5]:
# Divide the data into X as a data for learning models aka features and y as a data the model should predict aka target
X = data_snp_phenotype.drop(columns=["Accession", "Heterotic group"]) # Генотипы
y = data_snp_phenotype["Heterotic group"]  # гетерозисная группа

In [6]:
X

,NC_024459.2,NC_024459.2.1,NC_024459.2.2,NC_024459.2.3,NC_024459.2.4,NC_024459.2.5,NC_024459.2.6,NC_024459.2.7,NC_024459.2.8,NC_024459.2.9,...,NC_024468.2.13198,NC_024468.2.13199,NC_024468.2.13200,NC_024468.2.13201,NC_024468.2.13202,NC_024468.2.13203,NC_024468.2.13204,NC_024468.2.13205,NC_024468.2.13206,NC_024468.2.13207
0,1|0,1|1,1|0,0|1,1|1,1|0,1|0,1|0,1|0,1|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1,1|0,1|1,1|0,1|1,1|1,1|0,1|0,1|0,1|0,1|0,...,1|1,0|1,0|1,1|1,0|0,1|1,1|1,1|1,0|0,0|0
2,1|0,1|0,1|0,1|1,1|1,0|1,0|1,0|1,0|1,0|1,...,0|0,1|0,0|0,0|0,0|0,0|1,0|1,0|1,1|0,1|0
3,0|1,0|1,0|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
4,0|0,1|1,0|0,1|1,1|1,1|0,1|0,1|0,1|0,1|0,...,0|1,1|1,1|1,1|1,1|0,1|1,1|1,1|1,0|1,0|1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,0|1,1|1,0|1,1|1,1|1,0|1,0|1,0|1,0|1,0|1,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|1,0|1
601,0|1,1|1,0|1,1|1,1|1,0|1,0|1,0|1,0|1,0|1,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,1|0,1|0
602,1|0,1|1,1|0,1|1,1|1,1|0,1|0,1|0,1|0,1|0,...,1|1,0|0,1|1,1|1,0|0,1|1,1|1,1|1,1|0,1|0
603,1|0,1|0,1|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,1|0,1|0
604,0|1,0|1,0|1,0|1,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|1,0|1

In [7]:
y

0      NSS
1      SPT
2      NSS
3       PB
4       PA
      ...
600     PA
601     PA
602     PA
603     PA
604    NSS
Name: Heterotic group, Length: 605, dtype: object

In [8]:
def convert_genotype(genotype):
    """Конвертирует строку '1|0', '0|1', '1|1' и др. в категориальные значения"""
    if genotype == "1|1":
        return 0
    elif genotype == "1|0" or genotype == "0|1":
        return 1
    elif genotype == "0|0":
        return 2
    else:
        return 3

In [9]:
X.columns.astype('category')

CategoricalIndex(['NC_024459.2', 'NC_024459.2.1', 'NC_024459.2.2',
                  'NC_024459.2.3', 'NC_024459.2.4', 'NC_024459.2.5',
                  'NC_024459.2.6', 'NC_024459.2.7', 'NC_024459.2.8',
                  'NC_024459.2.9',
                  ...
                  'NC_024468.2.13198', 'NC_024468.2.13199',
                  'NC_024468.2.13200', 'NC_024468.2.13201',
                  'NC_024468.2.13202', 'NC_024468.2.13203',
                  'NC_024468.2.13204', 'NC_024468.2.13205',
                  'NC_024468.2.13206', 'NC_024468.2.13207'],
                 categories=['NC_024459.2', 'NC_024459.2.1', 'NC_024459.2.10', 'NC_024459.2.100', ..., 'NC_024468.2.9996', 'NC_024468.2.9997', 'NC_024468.2.9998', 'NC_024468.2.9999'], ordered=False, dtype='category', length=186200)

In [10]:
X = X.applymap(convert_genotype)

/tmp/ipykernel_3149078/251363383.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X = X.applymap(convert_genotype)

In [11]:
X

,NC_024459.2,NC_024459.2.1,NC_024459.2.2,NC_024459.2.3,NC_024459.2.4,NC_024459.2.5,NC_024459.2.6,NC_024459.2.7,NC_024459.2.8,NC_024459.2.9,...,NC_024468.2.13198,NC_024468.2.13199,NC_024468.2.13200,NC_024468.2.13201,NC_024468.2.13202,NC_024468.2.13203,NC_024468.2.13204,NC_024468.2.13205,NC_024468.2.13206,NC_024468.2.13207
0,1,0,1,1,0,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2
1,1,0,1,0,0,1,1,1,1,1,...,0,1,1,0,2,0,0,0,2,2
2,1,1,1,0,0,1,1,1,1,1,...,2,1,2,2,2,1,1,1,1,1
3,1,1,1,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
4,2,0,2,0,0,1,1,1,1,1,...,1,0,0,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,1,0,1,0,0,1,1,1,1,1,...,2,2,2,2,2,2,2,2,1,1
601,1,0,1,0,0,1,1,1,1,1,...,2,2,2,2,2,2,2,2,1,1
602,1,0,1,0,0,1,1,1,1,1,...,0,2,0,0,2,0,0,0,1,1
603,1,1,1,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,1,1
604,1,1,1,1,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,1,1

In [12]:
# Разделение данных на обучающую и тестовую выборки
# X - это признаки (фичи), y - целевая переменная (метка)
# test_size=0.2 означает, что 20% данных будет отведено под тестовую выборку
# random_state=42 обеспечивает воспроизводимость результатов
# stratify=y гарантирует, что пропорции классов в обучающей и тестовой выборках будут одинаковыми
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Инициализация модели CatBoostClassifier
# iterations=500 задает количество итераций (или деревьев), которые будут построены
# depth=5 определяет максимальную глубину деревьев, что влияет на сложность модели
# learning_rate=0.1 устанавливает скорость обучения, которая контролирует, насколько сильно модель будет корректировать свои предсказания
# loss_function='MultiClass' указывает, что задача является многоклассовой классификацией
# verbose=100 задает частоту вывода информации о процессе обучения (каждые 100 итераций)
# cat_features=list(X.columns) указывает, какие признаки являются категориальными
model = CatBoostClassifier(
    iterations=500,
    depth=5,
    learning_rate=0.1,
    loss_function='MultiClass',
    verbose=100,
    cat_features=list(X.columns),
    used_ram_limit='32gb', 
    thread_count=10 
)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
# Predicting the test data and checking the accuracy of predictions
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print(classification_report(y_test, y_pred))